Form validations
apepper/scrivito_example_app_js pull request #10
Opened 2022-01-03 16:09 UTC by apepper

This PR adds more validations to ensure, that the form in question is valid. E.g. it ensures, that one field name can only be used once and that a form container is not inside another form container.

Also the final API endpoint is in use now.

Locales are not yet checked by Andreas.

2022-01-05 15:03 UTC, dcsaszar requested changes
Looks good. Mostly FYI.

2022-01-05 15:03 UTC, dcsaszar commented on src/Widgets/FormContainerWidget/FormContainerWidgetEditingConfig.js
>          return "For form containers to work, a Neoletter instance must be specified in the site settings.";
* [ ] FYI unrelated idea: While testing I stumbled over the fact that "my first form" is red right from the start. How about moving this check to the submit button? This way, an editor is free to build a mostly working form without having to put dummy data, and an admin can set the API config independently to make the submit buttons work.

2022-01-06 12:44 UTC, apepper commented on src/Widgets/FormContainerWidget/validations/typeValidation.js
> +      return "There is at least one other element with the same input type.";
Both use-cases sound like a `custom single-line` but with more browser semantics (e.g. email or phone).

At least for now this is not yet planned.

2022-01-06 12:49 UTC, apepper commented on src/Widgets/FormContainerWidget/FormContainerWidgetEditingConfig.js
>          return "For form containers to work, a Neoletter instance must be specified in the site settings.";
Interesting idea. I like it.

2022-01-06 12:51 UTC, apepper commented
REVIEW (26ab333)

2022-01-07 16:14 UTC, dcsaszar approved these changes

2022-01-07 16:15 UTC, merged