Form builder: Allow hidden fields + smaller improvements
apepper/scrivito_example_app_js pull request #12
Opened 2022-01-13 12:03 UTC by apepper

https://user-images.githubusercontent.com/86275/149326855-c005fbcd-5d84-437c-abe9-eec93dfbcda3.mp4

2022-01-14 09:17 UTC, dcsaszar approved these changes
Technically OK, one suggestion.

* [ ] Regarding UX, we should rethink how editors manage hidden fields:

The current IPE approach is pragmatic and may work well for pragmatic editors. But is has some disadvantages:
1. Hidden fields provide DND, which has very limited use.
2. An editor has no indication about the content of a hidden field. You must look at the properties. This may get annoying as soon as you have more than one hidden field.

Ideas:
* Make use of titleForContent
* Have a visual representation of a hidden field in editing
* Put hidden fields into their own widgetlist form property
  * The visual representation will be in the properties, which matches the concept of "hidden" stuff
  * It may be conceptually more in line with the discussed feature of passing-on page query params

2022-01-14 09:17 UTC, dcsaszar commented on src/Widgets/FormCheckboxWidget/FormCheckboxWidgetEditingConfig.js
> +    ["customFieldName", { enabled: isCustomType(widget) }],
* [ ] FYI now that the input field widget uses a show/hide approach depending on the type (instead of enabled/disabled), we could do the same here for consistency.

2022-01-17 09:37 UTC, apepper commented
REVIEW (b9ecbbe)

2022-01-17 12:21 UTC, dcsaszar requested changes
See comments.

2022-01-17 13:49 UTC, apepper commented on src/Widgets/FormHiddenFieldWidget/FormHiddenFieldWidgetEditingConfig.js
> +    if (parts.length > 0) {
I didn't know, that `titleForContent` will also use the default title, if `titleForContent` returns `''`.

2022-01-17 13:50 UTC, apepper commented
REVIEW (226ae26)

2022-01-17 13:55 UTC, dcsaszar requested changes
Found one more. Apart from that LGTM

2022-01-17 13:55 UTC, dcsaszar commented on src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js
> +  }
* [ ] As an editor I'd expect an empty hidden field to still be submitted, like a left-blank text input.

2022-01-17 14:58 UTC, apepper commented
REVIEW (af638cc)

2022-01-17 15:33 UTC, dcsaszar approved these changes

2022-01-17 15:34 UTC, merged