Form view in neoletter
apepper/scrivito_example_app_js pull request #15
Opened 2022-02-17 10:02 UTC by apepper

<img width="1001" alt="view this form in neoletter v2" src="https://user-images.githubusercontent.com/86275/154452255-3674cebc-6f0e-4464-aaaa-3589049ae2ca.png">

2022-02-18 08:14 UTC, apepper commented
> How would a Scrivito user know that they need to register the form in Neoletter? If they click on the button for the first time the register page will be rendered in Neoletter. Is this enough to guide users?

I don't think, that this flow is ideal, yes. In my eyes the form should automatically be created in Neoletter, once the first submission arrives. Since this is not yet the case this button is the current work-around.

If you want to we can improve the wording of this button, e.g. `Register form or view form submission data`.

2022-02-18 09:39 UTC, dcsaszar requested changes
See comments for some rough edges. Also:

* [x] The component is not dynamically loaded which would increase the app bundle  size.
* [x] FYI hiding this essential feature in the "System" tab is not the best UX we can provide. Rename the tab to "Form submissions" or "Form data"?

2022-02-18 09:39 UTC, dcsaszar commented on src/Components/ScrivitoExtensions/SocialCardsTab.js
> +        <ValidationWarningIcon validations={validationsForCreator} />
I noticed that `validationsFor*` is badly named. This is now bleeding into more bad naming. `validations` ->  `validationResults`?
* [ ] Please improve readability

2022-02-18 09:39 UTC, dcsaszar commented on src/Components/ScrivitoExtensions/validationsHelper.js
> +  return <i className="scrivito_icon scrivito_icon_error"></i>;
Two things:

* [ ] FYI parts of the CSS come from non-public classes in `scrivito_editing.css`. This approach may break in the future. The Example App should make this practice look like a recommended approach.
* [ ] The code moved to `ScrivitoExtensions`, but the styles are still in `_social_cards.scss`

2022-02-18 09:39 UTC, dcsaszar commented on src/Widgets/FormContainerWidget/FormIdComponent.js
> +          className="btn btn-primary btn-sm"
* [ ] The button is styles like an app button. It should be styled like a UI button instead.
<img width="199" alt="image" src="https://user-images.githubusercontent.com/986170/154656667-95c53178-1d24-4bde-bc77-cc0bc4671063.png">

2022-02-18 13:24 UTC, apepper commented on src/Components/ScrivitoExtensions/SocialCardsTab.js
> +        <ValidationWarningIcon validations={validationsForCreator} />
I created a dedicated PR for this: https://github.com/Scrivito/scrivito_example_app_js/pull/450

2022-02-21 16:33 UTC, apepper commented
REVIEW (58d73c8)

I had to completely force-push [58d73c8](https://github.com/apepper/scrivito_example_app_js/pull/15/commits/58d73c89a5f81568ae220e48222881903fb48a48) since `[form_builder_master](https://github.com/apepper/scrivito_example_app_js/tree/form_builder_master)` now contains `ContentProperty`. It's probably best to review all commits anew.

2022-02-22 10:35 UTC, dcsaszar approved these changes
Looks good. One usability issue see comment.

* [ ] FYI Unrelated, already present in `form_builder_master`:
```
Uncaught TypeError: candidate.container is not a function
    at getFormContainer (getFormContainer.js:18:27)
```

2022-02-22 10:35 UTC, dcsaszar commented on src/Widgets/FormContainerWidget/FormIdComponent.js
> +      {neoletterInstance() && widget.get("formId") && (
* [ ] This is very confusing, because some editors see a button and some don't, without any indication why. A greyed-out button is a better alternative here.

2022-02-22 12:35 UTC, apepper commented
REVIEW ([2feaba4](https://github.com/apepper/scrivito_example_app_js/pull/15/commits/2feaba40df0e917003f78778d6ee107a7089bfa5))

2022-02-22 13:20 UTC, dcsaszar requested changes
Code looks good. Styles need a fix.

2022-02-22 13:20 UTC, dcsaszar commented on src/assets/stylesheets/_scrivito_extensions.scss
> +  @include box-shadow(0 0 5px rgba(0, 0, 0, 0.2));
* [ ] FYI as we only support modern browsers we can use native `box-shadow`

2022-02-22 13:20 UTC, dcsaszar commented on src/Widgets/FormContainerWidget/FormIdComponent.js
> +          className={`scrivito_button scrivito_blue${
<img width="721" alt="image" src="https://user-images.githubusercontent.com/986170/155139962-10cdddde-d0a0-43d8-ace7-86926de09775.png">

* [ ] Color and disabled should not go together or have a suitable precedence

2022-02-22 13:20 UTC, dcsaszar commented on src/assets/stylesheets/_scrivito_extensions.scss
> +  background: #eee;
* [ ] FYI See other comment. Looks weird to use `!important` for color but not bgcolor. In general `!important` is a smell, especially for simple CSS like here.

2022-02-23 13:40 UTC, apepper commented
REVIEW ([1c101ca](https://github.com/apepper/scrivito_example_app_js/pull/15/commits/1c101cab73bea23fe2f60a14db4e64df4bb25725))

2022-02-23 17:28 UTC, merged

2022-03-01 09:04 UTC, krishan commented
How did we end up with something long and convoluted like "Register form or view submissions" for the button?

Please keep CTAs simple and think about what the user _wants_.

Nobody wants to "register a form". The need to register a form arises because of technical limitations: Neoletter requires registration of forms, before it allows viewing the submissions. For technical reasons.

But the button label should reflect what the users _wants_ or _needs_ - and not some technical formalities that are requires along the way.

Please change the button label back to something simple.

2022-03-01 11:32 UTC, apepper commented
> How did we end up with something long and convoluted like "Register form or view submissions" for the button?

=> https://github.com/apepper/scrivito_example_app_js/pull/15#issuecomment-1043190488
=> https://github.com/apepper/scrivito_example_app_js/pull/15#issuecomment-1044117546
=> https://github.com/apepper/scrivito_example_app_js/pull/15#issuecomment-1044163337

I'm happy to change the button label yet again, but please @thomasritz and @krishan agree on a label first.

2022-03-01 12:13 UTC, thomasritz commented
IMO, since certain things won't happen automatically, the user should know that they need to take action. Not having a form created in Neoletter has implications: a) user can't see the form submissions, b) polling services (Pisa) don't know which form the submissions belong to.

For a), this is not critical. As soon as a user wants to see the submissions, Neoletter would ask them to register (create) the form. For this, the button could be labeled "View submissions".

For b), data could be misinterpreted. I could imagine that if submissions were fetched via API and an associated form couldn't be found, then the client wouldn't know what to do with it and maybe ignore the data. But this is probably also not that critical because initially, only test submissions are posted anyway.

So, if you prefer "View submissions" I'm okay with it.

2022-03-01 14:15 UTC, krishan commented
Yes, "View submissions" sounds good to me - anything simple really. 

I'm sure there are lots of subtleties, but trying to cram them in the label of a button doesn't make the UX better, in my experience.

2022-03-02 07:41 UTC, apepper commented
FYI: I changed it to "View submissions" in #16. The screenshot of this PR has been adjusted.