[FormContainer] Store a hidden "url" field
apepper/scrivito_example_app_js pull request #25
Opened 2022-09-26 15:02 UTC by apepper

During prerender it uses the URL of the containing obj. Once in a browser it will use the current window.location with pathname and search, but not hash.

See concept https://docs.google.com/document/d/1dpLXc9grQkUqxeuVX63lbPwFm--htFDpWdBpi-k-txw/edit#heading=h.jokyvkkj2bgb

2022-09-28 09:44 UTC, thomasritz commented
LGTM 😎

2022-09-28 17:43 UTC, dcsaszar requested changes
See comments.

2022-09-28 17:43 UTC, dcsaszar commented on src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js
> +        `${window.location.origin}${window.location.pathname}${window.location.search}`
* [ ] To a reader this looks unexpectedly complicated as there is `window.location.href`, which is even better since it includes the hash. Without the discussion in GDocs I would never have guessed that this is supposed to be a feature. Please note that proper libraries that put a token in a hash also remove the hash later on. I'd favor clear simplicity over mitigating low risk. If you disagree, please add an explanatory comment.

2022-09-28 17:43 UTC, dcsaszar commented on src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js
> +  React.useEffect(
* [ ] This is not a very reactive way of handling the location. If we put this widget in a layout component it is likely to submit the wrong URL. How about using the history as outlined here? https://help.mouseflow.com/en/articles/4310818-tracking-url-changes-with-react

2022-09-29 09:59 UTC, apepper commented on src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js
> +        `${window.location.origin}${window.location.pathname}${window.location.search}`
I'll use `window.location.href` then, including the hash. /cc @thomasritz

2022-09-29 11:39 UTC, thomasritz commented on src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js
> +        `${window.location.origin}${window.location.pathname}${window.location.search}`
I'm fine with both including and excluding the hash.

2022-10-06 08:40 UTC, apepper commented
Closing, so it can be resubmitted with the rebase `form_builder_master`.

2022-10-06 08:40 UTC, closed without merging