Form foundation
apepper/scrivito_example_app_js pull request #6
Opened 2021-12-03 13:45 UTC by apepper

This PR added `FormContainerWidget`, `FormSubmitButtonWidget` and a (basic) `FormTextInputWidget`.

The data is not yet submitted (to be done in a different PR). Also validations will be added at a later point in time.

See https://docs.google.com/document/d/1Dbr7Y-ODFsQ4YSyYtgfyWM74YwkZTCovSz4xstvkVzc/edit# for documentation of the API.

2021-12-06 14:28 UTC, dcsaszar requested changes
Looks good. See individual comments for suggestions and issues.

I intentionally didn't check the concept to make sure we have a generic approach that could be adapted to other form backends.

2021-12-06 14:28 UTC, dcsaszar commented on src/Widgets/FormTextInputWidget/FormTextInputWidgetComponent.js
> +            <PopoverBody>mandatory</PopoverBody>
* [ ] FYI if both "mandatory" and "description" are present the two adjacent popups may confuse users. I.e. users may miss one of them by clicking the other one. IMO combining the two popups could provide better UX.

2021-12-06 14:28 UTC, dcsaszar commented on src/Widgets/FormContainerWidget/FormContainerWidget.scss
> +}
* [ ] FYI currently, the look of this form is different from the look of the contact form. It would be nice to be consistent.

![image](https://user-images.githubusercontent.com/986170/144860405-23c3dc06-fad7-4271-895f-75fa6e1cb1d0.png)

2021-12-06 14:28 UTC, dcsaszar commented on src/Widgets/FormTextInputWidget/FormTextInputWidgetEditingConfig.js
> +    placeholder: "Your email address",
* [ ] FYI the contact form uses "Email" as placeholder

2021-12-06 14:28 UTC, dcsaszar commented on src/Widgets/FormTextInputWidget/FormTextInputWidgetClass.js
> +        values: ["email", "name"],
* [ ] FYI at this stage it feels weird that "name" is a type. In a generic form builder I'd expect a "text" type, where "name" is just one possible instance (via initial content or the widget library).

2021-12-06 14:28 UTC, dcsaszar commented on src/Widgets/FormTextInputWidget/FormTextInputWidgetClass.js
> +    description: "html",
* [ ] FYI "Description" is not very intuitive for the editor. We could rename it to `helpText`, or at least give it a more editor friendly title in the editing config.

2021-12-06 14:28 UTC, dcsaszar commented on src/Widgets/FormTextInputWidget/FormTextInputWidgetComponent.js
> +  const questionMarkId = `${id}_question_mark`;
* [ ] FYI we're mixing camel and underscore. Maybe stick with underscore.

2021-12-06 14:28 UTC, dcsaszar commented on src/assets/stylesheets/index.scss
> +.popover p { margin: 0; }
* [ ] FYI A pretty hard restriction which may lead to editors putting empty `p` for layout. How about:

```css
.popover p:last-of-type { margin: 0; }
```

2021-12-06 14:28 UTC, dcsaszar commented on src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js
> +  console.log("submitting", formProps);
* [ ] FYI currently, the editor can put multiple email and name inputs, but only one of them is included in the submitted data.

2021-12-06 15:38 UTC, apepper commented on src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js
> +  const [submission, setSubmission] = React.useState("not submitted");
Soon there will be multiple states: `submitting`, `success`, `failure` and `not submitted`. I don't see how boolean values will be practical here.

2021-12-06 15:40 UTC, apepper commented on src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js
> +    <div className="form-container-widget">
I already prepared a commit for a future PR. I'll already included in this PR.

2021-12-06 15:49 UTC, apepper commented on src/Widgets/FormContainerWidget/FormContainerWidgetEditingConfig.js
> +  title: "Form Container",
For editors `ColumnWidget` are hidden, leaving only `ColumnContainerWidget`. But forms can be in different forms and flavors. Also wording has already been checked with Andreas.

2021-12-06 15:52 UTC, apepper commented on src/Widgets/FormSubmitButtonWidget/FormSubmitButtonWidgetEditingConfig.js
> +  title: "Form: Submit Button",
With `Form: ` the widgets are "automatically" sorted correctly in the widgets sidebar.

2021-12-06 15:53 UTC, apepper commented on src/Widgets/FormSubmitButtonWidget/FormSubmitButtonWidgetEditingConfig.js
> +import formSubmitButtonWidgetIcon from "../../assets/images/form_submit_button_widget.svg";
The thumbnails have been provided by Alex G.. Please clarify with him, how the thumbnails should look like.

2021-12-06 15:54 UTC, apepper commented on src/Widgets/FormTextInputWidget/FormTextInputWidgetComponent.js
> +              <Scrivito.InPlaceEditingOff>
The popup would complete disappear if the editor removes the description. In this case the editor has only a change to re-add the description via the widget properties.

2021-12-06 15:56 UTC, apepper commented on src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js
> +  console.log("submitting", formProps);
Validations will be added in a later PR.

2021-12-06 16:01 UTC, apepper commented on src/Widgets/FormContainerWidget/FormContainerWidgetEditingConfig.js
> +    formId: () => random32CharHex(),
Where do you take the 13 K from? https://bundlephobia.com/package/@aws-sdk/util-hex-encoding@3.37.0 tells me, that the usage package `@aws-sdk/util-hex-encoding` is only 722 B minified (not even gzipped).

2021-12-06 18:02 UTC, dcsaszar commented on src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js
> +  const [submission, setSubmission] = React.useState("not submitted");
Boolean names are pretty clear: "Is the form being sent?", "Was the form sent?", "Was the form sent successfully?".
There may be invalid combinations but these are obvious, e.g. "The form was not sent and it was sent successfully."

To me, not being able to find good names for a non-boolean state is a smell. But we may try to fit every state in one value, how about `formSent`: The form was/is "never", "currently", "successfully", "unsuccessfully" sent?
There may be states that can't be covered by this approach though, e.g. "The form was already sent with an error and is being sent."

2021-12-06 21:14 UTC, dcsaszar commented on src/Widgets/FormContainerWidget/FormContainerWidgetEditingConfig.js
> +    formId: () => random32CharHex(),
webpack-bundle-analyzer

One of the bigger changes:
./node_modules/core-js (46.52 KB) -> ./node_modules/core-js (57.75 KB)

2021-12-06 21:35 UTC, dcsaszar commented on src/Widgets/FormSubmitButtonWidget/FormSubmitButtonWidgetEditingConfig.js
> +  title: "Form: Submit Button",
I never browsed the widget library like this, I always filter with the search. Grouping widgets by title appears to be a workaround for a missing widget grouping/hierarchy feature.

2021-12-06 21:37 UTC, dcsaszar commented on src/Widgets/FormTextInputWidget/FormTextInputWidgetComponent.js
> +              <Scrivito.InPlaceEditingOff>
Ideally the popup should not disappear if it is open. However, disappearing would still be good enough if the other issues can be fixed.

2021-12-07 09:55 UTC, apepper commented on src/Widgets/FormSubmitButtonWidget/FormSubmitButtonWidgetClass.js
> +      alignment: ["enum", { values: ["left", "center", "right"] }],
Good point. I created a PR to extend the original `ButtonWidget` with a `block` option. I'll also address it here as well.

2021-12-07 09:55 UTC, apepper commented on src/Widgets/FormSubmitButtonWidget/FormSubmitButtonWidgetEditingConfig.js
> +    alignment: "left",
I changed the default to "block".

2021-12-07 09:57 UTC, apepper commented on src/Widgets/FormContainerWidget/FormContainerWidget.scss
> +}
The form builder should use plain bootstrap classes as much as possible. Most designers will probably adjust the form design anyway.

2021-12-07 09:58 UTC, apepper commented on src/Widgets/FormTextInputWidget/FormTextInputWidgetClass.js
> +        values: ["email", "name"],
Please see the next PR for that.

2021-12-07 10:07 UTC, apepper commented on src/assets/stylesheets/index.scss
> +.popover p { margin: 0; }
Fine with me. How about you @agessler?

2021-12-07 10:07 UTC, apepper commented on src/Widgets/FormContainerWidget/FormContainerWidgetClass.js
> +    submittingMessage: "string",
This is an interesting idea. But for the start a single message should be good enough.

2021-12-07 10:08 UTC, agessler commented on src/assets/stylesheets/index.scss
> +.popover p { margin: 0; }
Like it!

2021-12-07 10:08 UTC, apepper commented on src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js
> +  if (submission === "submitting") {
This is an interesting idea. Especially if one extends the submittedMessage to a widgetlist. But for a first version this should be good enough.

2021-12-07 10:41 UTC, apepper commented on src/Widgets/FormContainerWidget/FormContainerWidgetEditingConfig.js
> +    formId: () => random32CharHex(),
Good point:

```
[src/Widgets/FormContainerWidget/random32CharHex.js]
The corejs3 polyfill added the following polyfills:
  es.array.iterator { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.object.to-string { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.uint8-array { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.copy-within { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.every { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.fill { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.filter { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.find { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.find-index { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.for-each { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.includes { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.index-of { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.iterator { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.join { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.last-index-of { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.map { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.reduce { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.reduce-right { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.reverse { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.set { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.slice { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.some { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.sort { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.subarray { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.to-locale-string { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
  es.typed-array.to-string { "android":"94", "chrome":"91", "edge":"92", "firefox":"78", "ie":"11", "ios":"12.2", "opera":"78", "safari":"13.1", "samsung":"14" }
```

2021-12-07 12:47 UTC, apepper commented on src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js
> +  const [submission, setSubmission] = React.useState("not submitted");
I gave it a try with boolean values - see next review.

2021-12-07 12:49 UTC, apepper commented on src/Widgets/FormContainerWidget/FormContainerWidgetEditingConfig.js
> +      description: "Autogenerated - modify with care",
I moved "formId" already to a "System" tab to mostly hide it from editors. Only power-user should change the Form ID if it's useful. The only use-case I can think of, is a deleted FormContainerWidget that later get's recreated by an editor - but the form ID of the original FormContainerWidget should be reused, so it appears as one and the same in Neoletter.

2021-12-07 12:52 UTC, apepper commented
REVIEW (c228520)

2021-12-07 12:56 UTC, apepper commented
REVIEW (87d70af)

Added some more design fixes by Alex G.

2021-12-08 07:25 UTC, dcsaszar requested changes
* [ ] See comments
* [ ] FYI Regarding https://github.com/apepper/scrivito_example_app_js/pull/6#discussion_r763036859, please remember Alex's choice to remove the old form CSS. Can be a follow-up though.

2021-12-08 07:25 UTC, dcsaszar commented on src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js
> +      failed();
* [ ] FYI the helper names are not self-explanatory enough to be understood without looking at the implementation. How about `indicate(Progress|Success|Failure|)`?

2021-12-08 07:25 UTC, dcsaszar commented on src/Widgets/FormContainerWidget/FormContainerWidgetEditingConfig.js
> +      title: "Message shown if form submission failed",
* [ ] FYI `submittedMessage` could mention "successfully" to make its use clearer

2021-12-08 07:25 UTC, dcsaszar commented on src/Widgets/FormContainerWidget/FormContainerWidgetEditingConfig.js
> +    failedMessage: "Form submission failed",
* [ ] FYI not very helpful or reassuring to the visitor. How about mentioning another channel or asking em to retry later?

2021-12-08 07:25 UTC, dcsaszar commented on src/assets/stylesheets/index.scss
> +  }
* [ ] FYI we're giving up separation of form widget specific CSS. We could either move these rules to `FormContainerWidget.scss`, or get rid of `FormContainerWidget.scss`

2021-12-08 07:25 UTC, dcsaszar commented on src/Widgets/FormContainerWidget/FormContainerWidgetEditingConfig.js
> +      description: "Autogenerated - modify with care",
* [ ] Your explanation is a good basis for a better description.

2021-12-09 13:35 UTC, apepper commented on src/Widgets/FormContainerWidget/FormContainerWidgetEditingConfig.js
> +    widget.update({ formId: md5(`${widget.obj().id()}${widget.id()}`) });
I don't wont to rely on the current widget/obj id format. It's actually not that important, that the formId is based on the obj or widget ID.

Therefore I switch back to `pseudoRandom32CharHex` but this time without an external library.

2021-12-09 13:39 UTC, apepper commented
REVIEW (8208a26)

Regarding the wording for editors/visitors I suggest that @dcsaszar, Andreas and I will talk on Friday in a Video chat.

2021-12-10 09:48 UTC, dcsaszar approved these changes

2021-12-10 09:54 UTC, merged